sonar.host.url=http://13.233.179.221:9000
sonar.projectKey=project:dev
sonar.projectName=project-dev
sonar.projectVersion=1.0
sonar.sources=./
sonar.java.binaries=.
sonar.sourceEncoding=UTF-8
sonar.login=sqa_453a62eaa705393a9b4942f6407e57ee83d3f443


